name: R Analytics Pipeline

on:
  # Run on push to main branch
  push:
    branches: [ main ]
  
  # Run on pull requests
  pull_request:
    branches: [ main ]
  
  # Manual trigger
  workflow_dispatch:
  
  # Scheduled run (daily at 6 AM UTC)
  schedule:
    - cron: '0 6 * * *'

jobs:
  podcast-analytics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
    
    - name: Cache R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1
        packages: |
          tidyverse
          httr
          jsonlite
          lubridate
          rmarkdown
    
    - name: Install R packages
      run: |
        Rscript -e "install.packages(c('tidyverse', 'httr', 'jsonlite', 'lubridate', 'rmarkdown'), repos='https://cran.r-project.org')"
    
    - name: Create output directories
      run: |
        mkdir -p data/raw data/processed reports
    
    - name: Run data fetch and analysis
      run: |
        Rscript scripts/fetch_and_analyze.R
      env:
        # Add your API keys as GitHub secrets and reference them here
        # SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        # SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        # ANCHOR_API_KEY: ${{ secrets.ANCHOR_API_KEY }}
    
    - name: Generate reports
      run: |
        Rscript -e "rmarkdown::render('scripts/report.Rmd', output_dir = 'reports')"
    
    - name: Upload analysis artifacts
      uses: actions/upload-artifact@v4
      with:
        name: podcast-analytics-${{ github.run_number }}
        path: |
          data/processed/
          reports/
        retention-days: 30
    
    - name: Upload reports to GitHub Pages (optional)
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: reports/
        
  # Optional: Deploy to GitHub Pages
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: podcast-analytics
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4